import type { Candidate, Session } from "./types";

type CandidateSeed = Omit<Candidate, "total">;

function computeTotal(scores: CandidateSeed["scores"]): number {
  const values = Object.values(scores);
  const avg = values.reduce((a, b) => a + b, 0) / values.length;
  return Math.round(avg);
}

function finalize(seeds: CandidateSeed[]): Candidate[] {
  return seeds
    .map((s) => ({ ...s, total: computeTotal(s.scores) }))
    .sort((a, b) => b.total - a.total);
}

const MOM_FITNESS: CandidateSeed[] = [
  {
    id: "SUBJECT-M001",
    text: "POV: You have 15 minutes and 3 kids screaming.",
    niche: "Mom Fitness",
    date: "2026-04-18",
    scores: {
      curiosity: 93,
      specificity: 88,
      patternInterrupt: 95,
      emotion: 91,
      stakes: 86,
    },
  },
  {
    id: "SUBJECT-M002",
    text: "I lost 27 pounds without giving up the food my kids beg for.",
    niche: "Mom Fitness",
    date: "2026-04-18",
    scores: {
      curiosity: 92,
      specificity: 90,
      patternInterrupt: 82,
      emotion: 84,
      stakes: 83,
    },
  },
  {
    id: "SUBJECT-M003",
    text: "The only fat-loss rule that matters if you're a mom.",
    niche: "Mom Fitness",
    date: "2026-04-18",
    scores: {
      curiosity: 94,
      specificity: 70,
      patternInterrupt: 80,
      emotion: 78,
      stakes: 82,
    },
  },
  {
    id: "SUBJECT-M004",
    text: "My nutritionist was furious I lost weight eating like this.",
    niche: "Mom Fitness",
    date: "2026-04-18",
    scores: {
      curiosity: 95,
      specificity: 76,
      patternInterrupt: 92,
      emotion: 86,
      stakes: 78,
    },
  },
  {
    id: "SUBJECT-M005",
    text: "Every mom I know tried this for 14 days. The before-after broke my DMs.",
    niche: "Mom Fitness",
    date: "2026-04-18",
    scores: {
      curiosity: 89,
      specificity: 85,
      patternInterrupt: 84,
      emotion: 82,
      stakes: 80,
    },
  },
  {
    id: "SUBJECT-M006",
    text: "Stop doing 'mom cardio'. It's making the belly worse.",
    niche: "Mom Fitness",
    date: "2026-04-18",
    scores: {
      curiosity: 91,
      specificity: 78,
      patternInterrupt: 94,
      emotion: 83,
      stakes: 85,
    },
  },
  {
    id: "SUBJECT-M007",
    text: "I did this 4-minute thing between nap times. Six weeks later my jeans fit.",
    niche: "Mom Fitness",
    date: "2026-04-18",
    scores: {
      curiosity: 88,
      specificity: 87,
      patternInterrupt: 83,
      emotion: 81,
      stakes: 77,
    },
  },
  {
    id: "SUBJECT-M008",
    text: "Three reasons your postpartum belly hasn't moved in 9 months.",
    niche: "Mom Fitness",
    date: "2026-04-18",
    scores: {
      curiosity: 92,
      specificity: 86,
      patternInterrupt: 72,
      emotion: 79,
      stakes: 84,
    },
  },
  {
    id: "SUBJECT-M009",
    text: "You're not lazy. Your cortisol is lying to you.",
    niche: "Mom Fitness",
    date: "2026-04-18",
    scores: {
      curiosity: 90,
      specificity: 68,
      patternInterrupt: 93,
      emotion: 88,
      stakes: 80,
    },
  },
  {
    id: "SUBJECT-M010",
    text: "The one grocery aisle I skip every week that dropped my cravings to zero.",
    niche: "Mom Fitness",
    date: "2026-04-18",
    scores: {
      curiosity: 87,
      specificity: 83,
      patternInterrupt: 78,
      emotion: 74,
      stakes: 72,
    },
  },
  {
    id: "SUBJECT-M011",
    text: "Trainers charge $300 for this. I'll give it to you in 30 seconds.",
    niche: "Mom Fitness",
    date: "2026-04-18",
    scores: {
      curiosity: 86,
      specificity: 89,
      patternInterrupt: 74,
      emotion: 72,
      stakes: 75,
    },
  },
  {
    id: "SUBJECT-M012",
    text: "If you can do a squat holding a toddler, you're already 80% there.",
    niche: "Mom Fitness",
    date: "2026-04-18",
    scores: {
      curiosity: 82,
      specificity: 78,
      patternInterrupt: 86,
      emotion: 76,
      stakes: 68,
    },
  },
];

const B2B_SAAS: CandidateSeed[] = [
  {
    id: "SUBJECT-S001",
    text: "I fired my top salesperson. Revenue went up 40% the next quarter.",
    niche: "B2B SaaS",
    date: "2026-04-15",
    scores: {
      curiosity: 94,
      specificity: 88,
      patternInterrupt: 91,
      emotion: 82,
      stakes: 89,
    },
  },
  {
    id: "SUBJECT-S002",
    text: "Our churn dropped 60% after we deleted our onboarding emails.",
    niche: "B2B SaaS",
    date: "2026-04-15",
    scores: {
      curiosity: 90,
      specificity: 89,
      patternInterrupt: 92,
      emotion: 66,
      stakes: 81,
    },
  },
  {
    id: "SUBJECT-S003",
    text: "The day we killed the free tier, MRR went up 3x.",
    niche: "B2B SaaS",
    date: "2026-04-15",
    scores: {
      curiosity: 91,
      specificity: 88,
      patternInterrupt: 87,
      emotion: 72,
      stakes: 84,
    },
  },
  {
    id: "SUBJECT-S004",
    text: "We stopped taking sales calls. Closed more deals than ever.",
    niche: "B2B SaaS",
    date: "2026-04-15",
    scores: {
      curiosity: 93,
      specificity: 71,
      patternInterrupt: 93,
      emotion: 70,
      stakes: 82,
    },
  },
  {
    id: "SUBJECT-S005",
    text: "Read the email your last churned customer sent. There's $200k in it.",
    niche: "B2B SaaS",
    date: "2026-04-15",
    scores: {
      curiosity: 90,
      specificity: 89,
      patternInterrupt: 76,
      emotion: 78,
      stakes: 88,
    },
  },
  {
    id: "SUBJECT-S006",
    text: "The SaaS pricing page mistake 9 out of 10 founders make.",
    niche: "B2B SaaS",
    date: "2026-04-15",
    scores: {
      curiosity: 89,
      specificity: 82,
      patternInterrupt: 70,
      emotion: 64,
      stakes: 76,
    },
  },
  {
    id: "SUBJECT-S007",
    text: "My co-founder quit. Best thing that happened to the company.",
    niche: "B2B SaaS",
    date: "2026-04-15",
    scores: {
      curiosity: 92,
      specificity: 72,
      patternInterrupt: 89,
      emotion: 86,
      stakes: 83,
    },
  },
  {
    id: "SUBJECT-S008",
    text: "One feature we built in 3 days now drives 38% of upgrades.",
    niche: "B2B SaaS",
    date: "2026-04-15",
    scores: {
      curiosity: 86,
      specificity: 91,
      patternInterrupt: 72,
      emotion: 64,
      stakes: 74,
    },
  },
  {
    id: "SUBJECT-S009",
    text: "We charge annually only. Here's what it did to customer quality.",
    niche: "B2B SaaS",
    date: "2026-04-15",
    scores: {
      curiosity: 85,
      specificity: 79,
      patternInterrupt: 80,
      emotion: 62,
      stakes: 80,
    },
  },
  {
    id: "SUBJECT-S010",
    text: "Your demo is the problem. Kill the demo.",
    niche: "B2B SaaS",
    date: "2026-04-15",
    scores: {
      curiosity: 83,
      specificity: 68,
      patternInterrupt: 92,
      emotion: 74,
      stakes: 70,
    },
  },
  {
    id: "SUBJECT-S011",
    text: "The Slack channel my entire sales team is silent in — on purpose.",
    niche: "B2B SaaS",
    date: "2026-04-15",
    scores: {
      curiosity: 88,
      specificity: 76,
      patternInterrupt: 84,
      emotion: 68,
      stakes: 66,
    },
  },
  {
    id: "SUBJECT-S012",
    text: "We A/B tested calling customers vs. ignoring them. The result was dark.",
    niche: "B2B SaaS",
    date: "2026-04-15",
    scores: {
      curiosity: 90,
      specificity: 84,
      patternInterrupt: 88,
      emotion: 83,
      stakes: 77,
    },
  },
];

const FINANCE: CandidateSeed[] = [
  {
    id: "SUBJECT-F001",
    text: "The $12 bank fee that's quietly costing you $47,000 in retirement.",
    niche: "Finance",
    date: "2026-04-12",
    scores: {
      curiosity: 92,
      specificity: 96,
      patternInterrupt: 71,
      emotion: 85,
      stakes: 93,
    },
  },
  {
    id: "SUBJECT-F002",
    text: "I have a 780 credit score and I still pay my bills late on purpose.",
    niche: "Finance",
    date: "2026-04-12",
    scores: {
      curiosity: 94,
      specificity: 82,
      patternInterrupt: 94,
      emotion: 78,
      stakes: 79,
    },
  },
  {
    id: "SUBJECT-F003",
    text: "Your 401(k) match is a trap if you're doing this one thing.",
    niche: "Finance",
    date: "2026-04-12",
    scores: {
      curiosity: 93,
      specificity: 70,
      patternInterrupt: 86,
      emotion: 80,
      stakes: 90,
    },
  },
  {
    id: "SUBJECT-F004",
    text: "I earn $220k and I carry a credit card balance. Here's why on purpose.",
    niche: "Finance",
    date: "2026-04-12",
    scores: {
      curiosity: 91,
      specificity: 88,
      patternInterrupt: 89,
      emotion: 74,
      stakes: 78,
    },
  },
  {
    id: "SUBJECT-F005",
    text: "The line on your pay stub nobody reads — and what it costs per year.",
    niche: "Finance",
    date: "2026-04-12",
    scores: {
      curiosity: 90,
      specificity: 86,
      patternInterrupt: 72,
      emotion: 76,
      stakes: 85,
    },
  },
  {
    id: "SUBJECT-F006",
    text: "Compound interest is not your friend. Here's why.",
    niche: "Finance",
    date: "2026-04-12",
    scores: {
      curiosity: 92,
      specificity: 66,
      patternInterrupt: 95,
      emotion: 78,
      stakes: 80,
    },
  },
  {
    id: "SUBJECT-F007",
    text: "I teach finance for a living. Here's the one bill I never pay off.",
    niche: "Finance",
    date: "2026-04-12",
    scores: {
      curiosity: 89,
      specificity: 72,
      patternInterrupt: 84,
      emotion: 72,
      stakes: 82,
    },
  },
  {
    id: "SUBJECT-F008",
    text: "The first $2,000 you save should never go into a savings account.",
    niche: "Finance",
    date: "2026-04-12",
    scores: {
      curiosity: 87,
      specificity: 84,
      patternInterrupt: 78,
      emotion: 66,
      stakes: 80,
    },
  },
  {
    id: "SUBJECT-F009",
    text: "Dave Ramsey is wrong about one thing. It's costing his fans $100k+.",
    niche: "Finance",
    date: "2026-04-12",
    scores: {
      curiosity: 91,
      specificity: 89,
      patternInterrupt: 86,
      emotion: 84,
      stakes: 86,
    },
  },
  {
    id: "SUBJECT-F010",
    text: "You don't have a money problem. You have a taxable-account problem.",
    niche: "Finance",
    date: "2026-04-12",
    scores: {
      curiosity: 86,
      specificity: 74,
      patternInterrupt: 82,
      emotion: 70,
      stakes: 77,
    },
  },
  {
    id: "SUBJECT-F011",
    text: "Three expenses under $50 that determine whether you'll ever be rich.",
    niche: "Finance",
    date: "2026-04-12",
    scores: {
      curiosity: 88,
      specificity: 82,
      patternInterrupt: 74,
      emotion: 72,
      stakes: 78,
    },
  },
  {
    id: "SUBJECT-F012",
    text: "I canceled my emergency fund. Best financial move of my thirties.",
    niche: "Finance",
    date: "2026-04-12",
    scores: {
      curiosity: 92,
      specificity: 76,
      patternInterrupt: 93,
      emotion: 81,
      stakes: 84,
    },
  },
];

const FOOD: CandidateSeed[] = [
  {
    id: "SUBJECT-D001",
    text: "Restaurant pasta hits different because of one ingredient you can buy for $4.",
    niche: "Food",
    date: "2026-04-08",
    scores: {
      curiosity: 89,
      specificity: 87,
      patternInterrupt: 68,
      emotion: 71,
      stakes: 62,
    },
  },
  {
    id: "SUBJECT-D002",
    text: "Why your scrambled eggs taste wrong — and the fix is ice cubes.",
    niche: "Food",
    date: "2026-04-08",
    scores: {
      curiosity: 91,
      specificity: 83,
      patternInterrupt: 92,
      emotion: 72,
      stakes: 60,
    },
  },
  {
    id: "SUBJECT-D003",
    text: "I put Michelin-chef salt on everything for a week. Here's what happened.",
    niche: "Food",
    date: "2026-04-08",
    scores: {
      curiosity: 88,
      specificity: 79,
      patternInterrupt: 80,
      emotion: 70,
      stakes: 58,
    },
  },
  {
    id: "SUBJECT-D004",
    text: "The steak you're ruining isn't the meat. It's the pan.",
    niche: "Food",
    date: "2026-04-08",
    scores: {
      curiosity: 87,
      specificity: 72,
      patternInterrupt: 91,
      emotion: 74,
      stakes: 66,
    },
  },
  {
    id: "SUBJECT-D005",
    text: "The Italian grandma secret the internet still doesn't know.",
    niche: "Food",
    date: "2026-04-08",
    scores: {
      curiosity: 92,
      specificity: 62,
      patternInterrupt: 76,
      emotion: 82,
      stakes: 58,
    },
  },
  {
    id: "SUBJECT-D006",
    text: "I tested 8 olive oils blind. The $9 one beat the $42 one.",
    niche: "Food",
    date: "2026-04-08",
    scores: {
      curiosity: 85,
      specificity: 93,
      patternInterrupt: 78,
      emotion: 68,
      stakes: 62,
    },
  },
  {
    id: "SUBJECT-D007",
    text: "The only three things you need to cook perfect rice. You own all three.",
    niche: "Food",
    date: "2026-04-08",
    scores: {
      curiosity: 86,
      specificity: 78,
      patternInterrupt: 72,
      emotion: 64,
      stakes: 56,
    },
  },
  {
    id: "SUBJECT-D008",
    text: "Your onions are burning because you're lying about the heat.",
    niche: "Food",
    date: "2026-04-08",
    scores: {
      curiosity: 84,
      specificity: 70,
      patternInterrupt: 88,
      emotion: 76,
      stakes: 54,
    },
  },
  {
    id: "SUBJECT-D009",
    text: "Stop buying chicken stock. The thing you throw away makes it better.",
    niche: "Food",
    date: "2026-04-08",
    scores: {
      curiosity: 88,
      specificity: 80,
      patternInterrupt: 86,
      emotion: 68,
      stakes: 64,
    },
  },
  {
    id: "SUBJECT-D010",
    text: "The dish every chef asks for on their last day off.",
    niche: "Food",
    date: "2026-04-08",
    scores: {
      curiosity: 90,
      specificity: 68,
      patternInterrupt: 72,
      emotion: 78,
      stakes: 54,
    },
  },
  {
    id: "SUBJECT-D011",
    text: "This 7-minute sauce replaces three jars in your fridge.",
    niche: "Food",
    date: "2026-04-08",
    scores: {
      curiosity: 82,
      specificity: 86,
      patternInterrupt: 72,
      emotion: 60,
      stakes: 52,
    },
  },
  {
    id: "SUBJECT-D012",
    text: "I went to a Tokyo ramen shop at 3am. The broth had exactly 4 ingredients.",
    niche: "Food",
    date: "2026-04-08",
    scores: {
      curiosity: 89,
      specificity: 94,
      patternInterrupt: 82,
      emotion: 72,
      stakes: 54,
    },
  },
];

export const SEED_SESSIONS: Session[] = [
  {
    id: "SESSION-0012",
    title: "Mom fitness · 2026-04-18",
    createdAt: "2026-04-18T09:30:00Z",
    updatedAt: "2026-04-18T09:42:00Z",
    brief: {
      niche: "Mom fitness",
      voice: "Direct, warm, no fluff",
      angle: "contrarian",
      taboo: "no weight-loss guilt, no crash-diet language",
      platform: "tiktok",
    },
    candidates: finalize(MOM_FITNESS),
    savedCandidateIds: ["SUBJECT-M001"],
  },
  {
    id: "SESSION-0011",
    title: "B2B SaaS · 2026-04-15",
    createdAt: "2026-04-15T14:12:00Z",
    updatedAt: "2026-04-15T14:22:00Z",
    brief: {
      niche: "B2B SaaS founder stories",
      voice: "Blunt, founder-to-founder, zero jargon",
      angle: "contrarian",
      taboo: "no buzzwords, no 'synergy'",
      platform: "reels",
    },
    candidates: finalize(B2B_SAAS),
    savedCandidateIds: [],
  },
  {
    id: "SESSION-0010",
    title: "Finance · 2026-04-12",
    createdAt: "2026-04-12T11:00:00Z",
    updatedAt: "2026-04-12T11:18:00Z",
    brief: {
      niche: "Personal finance for high earners",
      voice: "Advisor-peer, a little dry, always numerical",
      angle: "contrarian",
      taboo: "no get-rich-quick, no crypto shilling",
      platform: "shorts",
    },
    candidates: finalize(FINANCE),
    savedCandidateIds: ["SUBJECT-F009"],
  },
  {
    id: "SESSION-0009",
    title: "Food · 2026-04-08",
    createdAt: "2026-04-08T18:40:00Z",
    updatedAt: "2026-04-08T19:05:00Z",
    brief: {
      niche: "Home cooking with pro-chef technique",
      voice: "Curious, ingredient-nerdy, short sentences",
      angle: "educational",
      taboo: "no 'life hack' language",
      platform: "tiktok",
    },
    candidates: finalize(FOOD),
    savedCandidateIds: [],
  },
];

export const DEFAULT_ACTIVE_SESSION_ID = SEED_SESSIONS[0].id;
